name: Deployment pipeline
# 11.21 Protect your main branch and ask for pull reques pull requests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  lint_frontend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend/phonebook
        run: npm install

      - name: Check style
        working-directory: ./frontend/phonebook
        run: npm run lint

      - name: Notify Discord - Failure
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has failed linting the frontend.'

  lint_backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend/phonebook
        run: npm install

      - name: Check style
        working-directory: ./backend/phonebook
        run: npm run lint
      
      
      - name: Notify Discord - Failure
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has failed linting the backend.'

  building_app:
    needs: [lint_frontend, lint_backend]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install backend dependencies
        working-directory: ./backend/phonebook
        run: npm install

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend/phonebook

      - name: Building UI
        working-directory: ./backend/phonebook
        run: npm run build:ui

      - name: Notify Discord - Failure
        if: ${{ failure() }}
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
            args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has failed building the app.'
  
  deployment:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    needs: [building_app]
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    needs: [deployment]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Discord notification
        if: ${{ success() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'